<a href="https://colab.research.google.com/github/afcarioca/rf_learning/blob/main/rf_um_conto_de_natal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [150]:
### Importando Bibliotecas ###
import numpy as np
import random

In [151]:
### Ambiente ####
R = np.array([
    [-1, 0, -1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
    [ 0, -1, 0, -1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
    [ -1, 0, -1, 0, -1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1],
    [ -1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
    [ 0, -1, -1, -1, -1, 0, -1, -1, 0, -1, -1, -1, -1, -1, -1, -1],
    [ -1, 0, -1, -1, 0, -1, 0, -1, -1, 0, -1, -1, -1, -1, -1, -1],
    [ -1, -1, 0, -1, -1, 0, -1, -1, -1, -1, 0, -1, -1, -1, -1, -1],
    [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, -1, -1],
    [ -1, -1, -1, -1, 0, -1, -1, -1, -1, 0, -1, -1, 0, -1, -1, -1],
    [ -1, -1, -1, -1, -1, 0, -1, -1, 0, -1, 0, -1, -1, 0, -1, -1],
    [ -1, -1, -1, -1, -1, -1, 0, -1, -1, 0, -1, 0, -1, -1, 0, -1],
    [ -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, 0, -1, -1, -1, -1, 20],
    [ -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, -1, -1, 0, -1, -1],
    [ -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, 0, -1, 0, -1],
    [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, 0, -1, 20],
    [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 50],
])


In [152]:
### Memória ####
tabela_q = np.zeros_like(R)

In [153]:
### Configurações ####
alfa = 0.5
gama = 0.9
epsilon = 0.1
numero_episodios = 10000

In [154]:
### Escolha da ação a ser executada no Estado vigente ####
def escolhe_acao(estado, tabela_q):
  if random.uniform(0, 1) < epsilon:
     linhas, colunas = R.shape
     return random.randint(0 ,linhas-1)
  return np.argmax(tabela_q[estado])

In [155]:
### Treinando o modelo ###
def train(tabela_q, numero_episodios, alfa, gama, epsilon):
  for episodio in range(0, numero_episodios):
      estado = random.randint(0,15)

      while True:
        acao = escolhe_acao(estado, tabela_q)
        recompensa = R[estado, acao]

        if recompensa == -1:
          continue

        tabela_q[estado, acao] = (1- alfa) * tabela_q[estado, acao] + alfa *(recompensa + gama* np.max(tabela_q[acao,:]))
        estado = acao

        if estado == 7 or estado == 12 or estado == 15:
          break
  return tabela_q


In [156]:
### Normalização dos dados ###
def normalize(tabela):
  minimo = np.min(tabela)
  maximo = np.max(tabela)
  tabela = ((tabela - minimo) / (maximo - minimo))
  return (tabela *100).astype(int)

In [157]:
### Teste ####


def test(tabela):
  env = np.array([[0,4,8,12], [1,5,9,13], [2,6,10,14], [3,7,11,15]])

  for estado in range(0, env.size):
    env1 = np.array([["_", "_", "_", "T"],
                ["_", "_", "_", "_"],
                ["_", "_", "_", "_"],
                ["_", "T", "_", "X"]])

    linha_atual, coluna_atual = np.where(env == estado)
    env1[linha_atual, coluna_atual] = "o"
    episodio = 1
    print("-------")
    print("Início do Estado: {}".format(estado+1))
    print("-------")
    while True:

        print("Episódio: {}".format(episodio))
        print(env1)
        print("-----")
        print("Fim do Episódio")
        print("-----")

        if estado == 7 or estado == 12 or estado == 15:
          break

        acao = np.argmax(tabela[estado])
        env1[linha_atual, coluna_atual] = "_"
        estado = acao

        linha_atual, coluna_atual = np.where(env == estado)
        env1[linha_atual, coluna_atual] = "o"
        episodio+=1

    print("-------")
    print("Fim do Estado")
    print("-------")

In [158]:
if __name__ == "__main__":
  tabela_q = train(tabela_q, numero_episodios, alfa, gama, epsilon)
  tabela_q = normalize(tabela_q)
  print(tabela_q)
  print("-------")
  print("-------")
  print("-------")
  test(tabela_q)


[[  0  54   0   0  30   0   0   0   0   0   0   0   0   0   0   0]
 [ 48   0  60   0   0  60   0   0   0   0   0   0   0   0   0   0]
 [  0  54   0  54   0   0  67   0   0   0   0   0   0   0   0   0]
 [  0   0  60   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 48   0   0   0   0  60   0   0  59   0   0   0   0   0   0   0]
 [  0  53   0   0  52   0  67   0   0  67   0   0   0   0   0   0]
 [  0   0  60   0   0  60   0   0   0   0  75   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  83   0   0   0   0]
 [  0   0   0   0  51   0   0   0   0  67   0   0  54   0   0   0]
 [  0   0   0   0   0  60   0   0  60   0  75   0   0  60   0   0]
 [  0   0   0   0   0   0  67   0   0  67   0  83   0   0  83   0]
 [  0   0   0   0   0   0   0  75   0   0  75   0   0   0   0  93]
 [  0   0   0   0   0   0   0   0  60   0   0   0   0  30   0   0]
 [  0   0   0   0   0   0   0   0   0  67   0   0  52   0  65   0]
 [  0   0   0   0   0   0   0   0   0   0  72   0   0  45   0 